In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
# data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv'
# !wget $data -O course_lead_scoring_2026.csv

--2026-10-18 23:23:51--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 278746 (272K) [text/plain]
Saving to: ‘course_lead_scoring_2026.csv’

course_lead_scoring 100%[===================>] 272.21K  --.-KB/s    in 0.008s

2026-10-18 23:23:52 (34.8 MB/s) - ‘course_lead_scoring_2026.csv’ saved [278746/278746]

In [94]:
df = pd.read_csv('course_lead_scoring_2026.csv')
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [95]:
df.head(n=100).T

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
lead_source,organic_search,social_media,referral,paid_ads,referral,referral,NaN,paid_ads,organic_search,referral,...,organic_search,referral,organic_search,paid_ads,referral,paid_ads,referral,events,organic_search,events
industry,technology,technology,retail,manufacturing,manufacturing,manufacturing,education,technology,healthcare,retail,...,technology,education,finance,technology,education,retail,finance,technology,technology,retail
employment_status,employed,employed,employed,student,student,employed,employed,employed,employed,student,...,unemployed,self_employed,employed,unemployed,student,unemployed,employed,unemployed,employed,self_employed
location,europe,south_america,europe,NaN,north_america,africa,north_america,north_america,asia,asia,...,europe,europe,south_america,europe,africa,asia,asia,europe,europe,africa
annual_income,88160.0,72688.0,44697.0,NaN,24062.0,43841.0,58738.0,95059.0,62565.0,12000.0,...,53767.0,43499.0,59780.0,51151.0,NaN,21084.0,75202.0,50096.0,95649.0,34621.0
number_of_courses_viewed,3,3,3,3,4,3,3,2,3,2,...,3,1,2,1,3,4,2,1,1,2
interaction_count,4,7,4,6,5,5,9,4,6,2,...,5,8,4,5,3,9,5,0,1,4
lead_score,0.64,0.72,0.58,0.57,0.62,0.77,0.78,0.41,0.52,0.35,...,0.46,0.63,0.43,0.49,0.37,0.68,0.59,0.18,0.37,0.5
converted,1,1,1,0,1,1,1,1,1,0,...,0,1,0,0,0,1,1,0,1,1

In [96]:
df.columns.str.lower()

Index(['lead_source', 'industry', 'employment_status', 'location',
       'annual_income', 'number_of_courses_viewed', 'interaction_count',
       'lead_score', 'converted'],
      dtype='str')

In [97]:
# df.columns = df.columns.str.lower().str.replace(' ', '_')

# categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

# for c in categorical_columns:
#     df[c] = df[c].str.lower().str.replace(' ', '_')

In [98]:
categorical = list(df.dtypes[df.dtypes == 'str'].index)
categorical

['lead_source', 'industry', 'employment_status', 'location']

In [99]:
for c in categorical:
    df[c] = df[c].str.lower().str.replace(' ', '_')
    df[c] = df[c].fillna('NA')
    print(df[c].isna().sum())

0
0
0
0

In [100]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [101]:
numerical = ['annual_income', 'number_of_courses_viewed', 'interaction_count', 'lead_score']
for col in numerical:
    print(df[col].isna().sum())

369
0
0
35

In [102]:
df['lead_score'].isna().sum()

np.int64(35)

In [103]:
df['annual_income'] = df['annual_income'].fillna(0)

In [104]:
df['lead_score'] = df['lead_score'].fillna(0)

In [105]:
df.head(n=50)

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NA,0.0,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
5,referral,manufacturing,employed,africa,43841.0,3,5,0.77,1
6,NA,education,employed,north_america,58738.0,3,9,0.78,1
7,paid_ads,technology,employed,north_america,95059.0,2,4,0.41,1
8,organic_search,healthcare,employed,asia,62565.0,3,6,0.52,1
9,referral,retail,student,asia,12000.0,2,2,0.35,0
10,referral,retail,NA,europe,43935.0,2,9,0.78,1
11,paid_ads,technology,employed,asia,80773.0,3,7,0.72,1
12,social_media,NA,employed,africa,47115.0,1,0,0.11,0
13,paid_ads,retail,employed,north_america,62439.0,1,2,0.33,0
14,paid_ads,retail,student,asia,12000.0,0,1,0.13,0
15,organic_search,retail,employed,north_america,59239.0,3,9,0.85,1
16,organic_search,education,employed,asia,37431.0,3,5,0.55,0
17,organic_search,finance,employed,north_america,83331.0,3,5,0.56,1
18,referral,manufacturing,employed,africa,49038.0,2,3,0.50,1
19,social_media,finance,unemployed,asia,50544.0,2,2,0.40,1
20,social_media,education,employed,africa,31638.0,2,4,0.47,1
21,social_media,healthcare,employed,south_america,65430.0,3,5,0.73,1
22,social_media,healthcare,employed,asia,57952.0,2,5,0.56,1
23,referral,healthcare,student,europe,0.0,3,10,0.76,1
24,organic_search,technology,employed,asia,65713.0,4,7,0.74,1
25,referral,retail,student,asia,0.0,2,5,0.53,1
26,organic_search,retail,employed,africa,42510.0,4,5,0.60,1
27,paid_ads,education,employed,south_america,45257.0,1,2,0.32,0
28,paid_ads,NA,self_employed,europe,82749.0,1,1,0.34,0
29,referral,manufacturing,employed,asia,45317.0,2,8,0.83,1
30,social_media,NA,student,south_america,51061.0,1,2,0.37,1
31,events,education,employed,africa,13171.0,3,5,0.50,0
32,social_media,retail,self_employed,africa,33862.0,3,5,0.50,1
33,paid_ads,healthcare,employed,europe,68156.0,1,5,0.48,0
34,paid_ads,retail,unemployed,asia,26032.0,2,4,0.40,0
35,organic_search,healthcare,employed,north_america,65643.0,2,6,0.62,0
36,social_media,education,self_employed,south_america,39539.0,3,4,0.37,0
37,organic_search,healthcare,employed,europe,47583.0,2,5,0.60,1
38,paid_ads,technology,employed,north_america,92267.0,3,3,0.42,0
39,referral,education,self_employed,north_america,61949.0,1,2,0.38,0
40,paid_ads,technology,unemployed,north_america,39207.0,1,4,0.30,0
41,paid_ads,education,student,europe,12000.0,1,0,0.11,0
42,paid_ads,technology,employed,europe,73254.0,2,4,0.48,0
43,social_media,finance,self_employed,south_america,56082.0,3,5,0.49,0
44,social_media,manufacturing,student,asia,14763.0,2,5,0.42,0
45,social_media,education,employed,north_america,53769.0,3,6,0.55,0
46,events,education,employed,africa,40215.0,3,6,0.54,1
47,organic_search,finance,self_employed,north_america,67761.0,4,8,0.83,0
48,social_media,education,student,south_america,12000.0,1,0,0.16,1
49,social_media,finance,employed,europe,69440.0,2,6,0.55,1

In [106]:
# Q1: What is the most frequent observation (mode) for the column industry?
df['industry'].mode()

0    technology
Name: industry, dtype: str

In [107]:
from sklearn.model_selection import train_test_split
# split the data
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

In [108]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [109]:
# extract the target variable or `converted` column
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

In [110]:
# EDA
# Use the training and validation dataset together
df_full_train = df_full_train.reset_index(drop=True)

In [111]:
# EDA - look at the target variable 'converted'
df_full_train.converted.value_counts(normalize=True)

converted
1    0.57075
0    0.42925
Name: proportion, dtype: float64

In [112]:
df_full_train.converted.mean()

np.float64(0.57075)

In [113]:
# del df_train['converted']
# del df_full_train['converted']
# del df_val['converted']
# del df_test['converted']

In [114]:
# Correlation of Numerical Features with 'converted'
df_full_train[numerical].corrwith(df_full_train.converted)

annual_income               0.188437
number_of_courses_viewed    0.393200
interaction_count           0.450273
lead_score                  0.482078
dtype: float64

In [115]:
from sklearn.metrics import mutual_info_score

In [116]:
def mutual_info_converted_score(series):
    return mutual_info_score(series, df_full_train.converted)

In [118]:
mi = df_full_train[categorical].apply(mutual_info_converted_score)
mi.sort_values(ascending=False)

lead_source          0.034761
employment_status    0.020313
industry             0.002898
location             0.001050
dtype: float64

In [119]:
# One-hot encode the categoriacl columns into multiple binary columns
dicts = df[categorical + numerical].to_dict(orient='records')

In [120]:
from sklearn.feature_extraction import DictVectorizer

In [131]:
dv = DictVectorizer(sparse=False)
all_categories = categorical + numerical
all_categories

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

['lead_source',
 'industry',
 'employment_status',
 'location',
 'annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

In [122]:
# get the names of all the columns
dv.get_feature_names_out()

array(['annual_income', 'employment_status=NA',
       'employment_status=employed', 'employment_status=self_employed',
       'employment_status=student', 'employment_status=unemployed',
       'industry=NA', 'industry=education', 'industry=finance',
       'industry=healthcare', 'industry=manufacturing', 'industry=retail',
       'industry=technology', 'interaction_count', 'lead_score',
       'lead_source=NA', 'lead_source=events',
       'lead_source=organic_search', 'lead_source=paid_ads',
       'lead_source=referral', 'lead_source=social_media', 'location=NA',
       'location=africa', 'location=asia', 'location=europe',
       'location=north_america', 'location=south_america',
       'number_of_courses_viewed'], dtype=object)

In [123]:
X_train.shape

(3000, 28)

In [124]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [125]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [126]:
model.intercept_[0]

np.float64(-0.010838978497809288)

In [127]:
model.coef_[0].round(3)

array([-0.   , -0.001,  0.007, -0.003, -0.008, -0.006, -0.   , -0.003,
       -0.001, -0.002, -0.002, -0.002, -0.001,  0.137,  0.011,  0.   ,
       -0.009,  0.007, -0.014,  0.009, -0.004,  0.   , -0.002, -0.002,
       -0.001, -0.003, -0.004,  0.054])

In [128]:
y_pred = model.predict_proba(X_val)[:, 1]

In [129]:
converted_decision = (y_pred >= 0.5)

In [130]:
# measuring accuracy of the trained model on the validation set
(y_val == converted_decision).mean()

np.float64(0.645)

In [132]:
# Use the feature elimination to determine the least useful feature
dv = DictVectorizer(sparse=False)
all_categories = categorical + numerical
all_categories.remove('interaction_count')

train_dict = df_train[all_categories].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [133]:
# get the names of all the columns
dv.get_feature_names_out()

array(['annual_income', 'employment_status=NA',
       'employment_status=employed', 'employment_status=self_employed',
       'employment_status=student', 'employment_status=unemployed',
       'industry=NA', 'industry=education', 'industry=finance',
       'industry=healthcare', 'industry=manufacturing', 'industry=retail',
       'industry=technology', 'lead_score', 'lead_source=NA',
       'lead_source=events', 'lead_source=organic_search',
       'lead_source=paid_ads', 'lead_source=referral',
       'lead_source=social_media', 'location=NA', 'location=africa',
       'location=asia', 'location=europe', 'location=north_america',
       'location=south_america', 'number_of_courses_viewed'], dtype=object)

In [134]:
X_train.shape

(3000, 27)

In [135]:
val_dict = df_val[all_categories].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [136]:
# retrain the model on the training set without the feature in X
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [137]:
y_pred = model.predict_proba(X_val)[:, 1]

In [138]:
converted_decision = (y_pred >= 0.5)

In [139]:
# measuring accuracy of the trained model on the validation set
(y_val == converted_decision).mean()

np.float64(0.601)

In [140]:
# Use the feature elimination to determine the least useful feature
dv = DictVectorizer(sparse=False)
all_categories = categorical + numerical
all_categories.remove('number_of_courses_viewed')

train_dict = df_train[all_categories].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [141]:
# get the names of all the columns
dv.get_feature_names_out()

array(['annual_income', 'employment_status=NA',
       'employment_status=employed', 'employment_status=self_employed',
       'employment_status=student', 'employment_status=unemployed',
       'industry=NA', 'industry=education', 'industry=finance',
       'industry=healthcare', 'industry=manufacturing', 'industry=retail',
       'industry=technology', 'interaction_count', 'lead_score',
       'lead_source=NA', 'lead_source=events',
       'lead_source=organic_search', 'lead_source=paid_ads',
       'lead_source=referral', 'lead_source=social_media', 'location=NA',
       'location=africa', 'location=asia', 'location=europe',
       'location=north_america', 'location=south_america'], dtype=object)

In [142]:
X_train.shape

(3000, 27)

In [143]:
val_dict = df_val[all_categories].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [144]:
# retrain the model on the training set without the feature, 'number_of_courses_viewed') in X
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [145]:
y_pred = model.predict_proba(X_val)[:, 1]

In [146]:
converted_decision = (y_pred >= 0.5)

In [147]:
# measuring accuracy of the trained model on the validation set
(y_val == converted_decision).mean()

np.float64(0.643)

In [148]:
# Use the feature elimination to determine the least useful feature
dv = DictVectorizer(sparse=False)
all_categories = categorical + numerical
all_categories.remove('lead_source')

train_dict = df_train[all_categories].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [149]:
# get the names of all the columns
dv.get_feature_names_out()

X_train.shape

(3000, 22)

In [150]:
val_dict = df_val[all_categories].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [151]:
# retrain the model on the training set without the feature, 'number_of_courses_viewed') in X
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [152]:
y_pred = model.predict_proba(X_val)[:, 1]

In [153]:
converted_decision = (y_pred >= 0.5)

In [154]:
# measuring accuracy of the trained model on the validation set
(y_val == converted_decision).mean()

np.float64(0.642)

In [159]:
# Feature importance
# difference b/w original model accuracy and accuracy after removing feature:
# a.) 'interaction_count'
model_accuracy_without_interaction_count = 0.645 - 0.601
model_accuracy_without_interaction_count

0.04400000000000004

In [160]:
# b.) 'number_of_courses_viewed'
model_accuracy_without_number_of_courses_viewed = 0.645 - 0.643
model_accuracy_without_number_of_courses_viewed

0.0020000000000000018

In [161]:
# c.) 'lead_source'
model_accuracy_without_lead_source = 0.645 - 0.642
model_accuracy_without_lead_source

0.0030000000000000027

In [162]:
# Q6. Regularized Logistic Regression model
C = [0.000001, 0.00001, 0.0001, 0.001]

In [163]:
model = LogisticRegression(solver='liblinear', C=0.000001, max_iter=1000, random_state=42)

In [164]:
dv = DictVectorizer(sparse=False)
all_categories = categorical + numerical
all_categories

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [165]:
# get the names of all the columns
dv.get_feature_names_out()

array(['annual_income', 'employment_status=NA',
       'employment_status=employed', 'employment_status=self_employed',
       'employment_status=student', 'employment_status=unemployed',
       'industry=NA', 'industry=education', 'industry=finance',
       'industry=healthcare', 'industry=manufacturing', 'industry=retail',
       'industry=technology', 'interaction_count', 'lead_score',
       'lead_source=NA', 'lead_source=events',
       'lead_source=organic_search', 'lead_source=paid_ads',
       'lead_source=referral', 'lead_source=social_media', 'location=NA',
       'location=africa', 'location=asia', 'location=europe',
       'location=north_america', 'location=south_america',
       'number_of_courses_viewed'], dtype=object)

In [166]:
X_train.shape

(3000, 28)

In [167]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [168]:
# Fit the model
model.fit(X_train, y_train)

LogisticRegression(C=1e-06, max_iter=1000, random_state=42, solver='liblinear')

In [169]:
y_pred = model.predict_proba(X_val)[:, 1]

converted_decision = (y_pred >= 0.5)

# measuring accuracy of the trained model on the validation set
(y_val == converted_decision).mean()

np.float64(0.598)

In [171]:
# C = 0.00001
model = LogisticRegression(solver='liblinear', C=0.00001, max_iter=1000, random_state=42)

# Fit the model
model.fit(X_train, y_train)

y_pred = model.predict_proba(X_val)[:, 1]

converted_decision = (y_pred >= 0.5)

# measuring accuracy of the trained model on the validation set
(y_val == converted_decision).mean()

np.float64(0.598)

In [172]:
# C = 0.0001
model = LogisticRegression(solver='liblinear', C=0.0001, max_iter=1000, random_state=42)

# Fit the model
model.fit(X_train, y_train)

y_pred = model.predict_proba(X_val)[:, 1]

converted_decision = (y_pred >= 0.5)

# measuring accuracy of the trained model on the validation set
(y_val == converted_decision).mean()

np.float64(0.613)

In [174]:
# C = 0.001 <--- Best accuracy
model = LogisticRegression(solver='liblinear', C=0.001, max_iter=1000, random_state=42)

# Fit the model
model.fit(X_train, y_train)

y_pred = model.predict_proba(X_val)[:, 1]

converted_decision = (y_pred >= 0.5)

# measuring accuracy of the trained model on the validation set
(y_val == converted_decision).mean()

np.float64(0.645)